### ISSUE TITLE
How can I add "image" field to the graph API? 

### ISSUE THREAD

**Issue by caalvinz** [vuestorefront-community/odoo#37]
### What is your question / Please describe your issue

I want to list the categories with image on the front end. The current graph API doesn't return image field.

I tried expend the fields on the file "schemas/objects.py" with the following codes:
```
# line 198
class Category(OdooObjectType):
    # ....
    image = graphene.String()
    small_image = graphene.String()
    thumbnail = graphene.String()

    def resolve_id(self, info):
        return self.id or None

    def resolve_image(self, info):
        if self.image_1920:
            return '/web/image/category.image/{}/image_1920'.format(self.id)
        return None

    def resolve_small_image(self, info):
        if self.image_1920:
            return '/web/image/{}/{}/image_128'.format(self._name, self.id)
        return None

    def resolve_thumbnail(self, info):
        if self.image_1920:
            return '/web/image/{}/{}/image_512'.format(self._name, self.id)
        return None
```
And upgraded the module on odoo. The new fields didn't show up on the API.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/4986240/164336662-51604194-cd4b-432e-a11e-baa7d4edfd8f.png">

Is there anybody can help? Thanks. 

### What version of odoo integration are you using?

15.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odranoelBR** [comment]
Please @caalvinz report on https://github.com/odoogap/vuestorefront
We really don't use category images by default, but for sure, it's doable / customisable.

After return them in the api, we must update query our create a custom query.
Tks
