### ISSUE TITLE
[Bug]: Incorrect special price

### ISSUE THREAD

**Issue by themreza** [vuestorefront-community/odoo#39]
### Expected Behavior

The regular price should not be scratched off if it's the same as the special price.
To be more specific, no special price should be returned if it's not less than the regular price.

### Actual Behavior

The same price is used for both special and regular attributes of the SfPrice component.

![image](https://user-images.githubusercontent.com/5465057/168067048-d67fa8dc-4637-449b-98db-0808028ef133.png)

### Possible Solution

Modify the `getPrice` method of `productGetters`.

https://github.com/vuestorefront-community/odoo/blob/dc0d43e7632f7183b57542bc6e508f2ec0afb076/packages/composables/src/composables/getters/productGetters.ts#L30

### What version of odoo integration are you using?

14.0

### What version of Node.js are you using?

12

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odranoelBR** [comment]
tks @themreza fixed in https://github.com/vuestorefront-community/template-odoo/pull/17
