### ISSUE TITLE
[Bug]: Billing form - Default customer informations are not blank

### ISSUE THREAD

**Issue by SullyAnn** [vuestorefront-community/odoo#40]
### Expected Behavior

The customer information should be by default blank.

### Actual Behavior

The customer information are by default the one of public user. 
As we can see below, the first name by default is " public user" . Since this user does not have other information the other fields of the form are empty.
![Billing_form_issue](https://user-images.githubusercontent.com/77010701/172824197-a19b1d31-d4e1-4821-ad87-f924a02d8566.png)

### What version of odoo integration are you using?

14.0

### What version of Node.js are you using?

v12.22.12

### What browser (and version) are you using?

Chrome version 101.0.4951.64

### What operating system (and version) are you using?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odranoelBR** [comment]
Hi @SullyAnn Tks for the PR, we are going to update to SFUI2.
