### ISSUE TITLE
SEO friendly (Custom URLs)

### ISSUE THREAD

**Issue by ska-ibees** [vuestorefront-community/odoo#48]
### What is your question / Please describe your issue

Is it possible to define completely different URLs within vuestorefront? 

For example:

shop/product/iphone-11 => /iphone
shop/category/computers-12 => /desktop-computers
blog/our-blog-1/post/the-future-of-internet-1 => /future-of-internet 

### What version of odoo integration are you using?

15.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odranoelBR** [comment]
Hi @ska-ibees , yes it is, we have a feature to generate routes based on configuration in odoo.
In you example, you can have computers-12 category configured in odoo with the slug /desktop-computers.
The vsf will read this value to create the route.
