### ISSUE TITLE
[Bug]: Getting this error in Heroku builds

### ISSUE THREAD

**Issue by bootsmann1995** [vuestorefront-community/odoo#50]
### Expected Behavior

I set the PORT env variable in horoku but it doesnt apply to th listening port. 

Works fine in localhost (npm run dev)

but npm run build && npm start gives the error shown in next section.

### Actual Behavior

it listens to a whole other port than defined

![image](https://user-images.githubusercontent.com/65391517/191948785-e8c65a89-c3db-4e20-ae13-bed021dcfd31.png)

process.env.PORT = 8000

### What version of odoo integration are you using?

1.4.1

### What version of Node.js are you using?

16.13

### What browser (and version) are you using?

all

### What operating system (and version) are you using?

windows / horoku

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dduarte-odoogap** [comment]
Hi @bootsmann1995 
I haven't tried using Heroku, but you should use the following node version: v14.19.0
